export const global = {
  size: {
    xxxxs: "0.25em",
    xxxs: "0.5em",
    xxs: "0.75em",
    xs: "0.875em",
    s: "1em",
    m: "1.5em",
    l: "2em",
    xl: "2.5em",
    xxl: "3em",
    xxxl: "3.5em",
    xxxxl: "4em",
    ul: "4.5em",
    uul: "5em",
    uuul: "5.5em",
  },
}

export default {
  breakpoint: {
    xxs: "320px",
    xs: "420px",
    s: "540px",
    m: "720px",
    l: "946px",
    xl: "1100px",
    globalNav: "720px",
    contentCard: "720px",
    collapsedCard: "720px",
    dropMenu: "420px",
  },
  colour: {
    primary: {
      colour: "hsl(223 100% 50%)",
      scheme: "dark",
    },
    accent: {
      colour: "hsl(60, 94%, 68%)",
      scheme: "light",
    },
    main: {
      fg: "hsl(60 30% 6%)",
      bg: "hsl(60 0% 100%)",
      fgAlt: "hsl(60 30% 20%)",
      bgAlt: "hsl(60 30% 95%)",
      border: "hsl(60 5% 85%)",
      scheme: "light",
    },
    reverse: {
      fg: "hsl(60 0% 100%)",
      bg: "hsl(60 30% 6%)",
      fgAlt: "hsl(60 5% 60%)",
      bgAlt: "hsl(60 0% 5%)",
      border: "hsl(60 0% 20%)",
      scheme: "dark",
    },
    info: "hsl(223 100% 50%)",
    warning: "hsl(35 100% 32%)",
    success: "hsl(120 100% 26%)",
    error: "hsl(348 100% 33%)",
  },
  font: {
    family: "system-ui, sans-serif",
    lineHeight: {
      main: "1.6",
      heading: "1.2",
      ui: "0.9rem",
    },
    weight: {
      main: 400,
      bold: 700,
    },
    size: {
      ratioSmall: 1.125,
      ratio: 1.25,
      basePx: "16px",
      diff: 0.3,
    },
  },
  size: {
    spacing: {
      xxxxs: global.size.xxxxs,
      xxxs: global.size.xxxs,
      xxs: global.size.xxs,
      xs: global.size.xs,
      s: global.size.s,
      m: global.size.m,
      l: global.size.l,
      xl: global.size.xl,
      xxl: global.size.xxl,
      xxxl: global.size.xxxl,
      xxxxl: global.size.xxxxl,
      ul: global.size.ul,
      uul: global.size.uul,
      uuul: global.size.uuul,
    },
    gap: {
      s: global.size.s,
      m: global.size.m,
      l: global.size.l,
      xl: global.size.xl,
    },
    container: {
      plus: "12rem",
      minus: "8rem",
      aligned: "76ch",
      narrow: "58ch",
      gutterMin: global.size.s,
      gutterMax: global.size.l,
    },
  },
  utility: {
    outline: {
      width: "2px",
      style: "solid",
      colour: "hsl(223 100% 50%)",
    },
    radius: {
      m: "4px",
      l: global.size.l,
      round: "50%",
    },
    shadow: {
      colour: "hsl(0 0% 13% / 15%)",
      size: global.size.xs,
    },
    ratio: "16 / 9",
  },
}
